#!/bin/zsh
# vim:ft=sh

if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" &&
        print -P "%F{33} %F{34}Installation successful.%f%b" ||
        print -P "%F{160} The clone has failed.%f%b"
fi
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
# autoload -Uz _zinit
# (( ${+_comps} )) && _comps[zinit]=_zinit

# load first
if [[ -f /usr/bin/fzf ]]; then
    zinit light Aloxaf/fzf-tab
fi

# zinit load starship/starship

# load from repository
zinit light-mode for \
    zsh-users/zsh-autosuggestions \
    zdharma-continuum/history-search-multi-word \
    zdharma-continuum/fast-syntax-highlighting # highlight zsh cli

zinit light skywind3000/z.lua # env settings in shell_env

# use .autoenv.zsh and .autoenv_leave.zsh
zinit light Tarrasch/zsh-autoenv

# zinit light spaceship-prompt/spaceship-prompt

# load sub plugins from oh-my-zsh
# zinit snippet OMZP::git
zinit snippet OMZP::extract
# zinit snippet OMZP::tmux

ENABLE_CORRECTION="true"
zinit snippet OMZL::completion.zsh
# zinit snippet OMZL::clipboard.zsh
# zinit snippet OMZL::termsupport.zsh
zinit snippet OMZL::history.zsh
# zinit snippet OMZL::grep.zsh

zinit ice lucid wait as'completion' blockf has'lcode'
zinit snippet https://github.com/saying121/lcode/blob/main/completions/_lcode

# zinit ice lucid wait as'completion' blockf has'task'
# zinit snippet https://github.com/go-task/task/blob/main/completion/zsh/_task

##############################################################################

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust
